//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Permiso
    {
        public int id { get; set; }
        public Nullable<int> rol_id { get; set; }
        public string modulo { get; set; }
        public string permiso { get; set; }
    
        public virtual Adm_Rol Adm_Rol { get; set; }
    }
}
