//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Permiso
    {
        public int id { get; set; }
        public Nullable<int> rol_id { get; set; }
        public string modulo { get; set; }
        public string permiso { get; set; }
    
        public virtual Adm_Rol Adm_Rol { get; set; }
    }
}
