//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Venta_Producto
    {
        public int id_producto { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> inventario { get; set; }
        public string motivo { get; set; }
        public System.DateTime fecha { get; set; }
        public int responsable { get; set; }
    }
}
