//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Venta_Producto
    {
        public int id_producto { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> inventario { get; set; }
        public string motivo { get; set; }
        public System.DateTime fecha { get; set; }
        public int responsable { get; set; }
    }
}
