//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta_Transaccion
    {
        public int id { get; set; }
        public int tipo_transaccion { get; set; }
        public Nullable<int> compra_id { get; set; }
        public Nullable<int> venta_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string descripcion { get; set; }
    
        public virtual Conta_TipoTransaccion Conta_TipoTransaccion { get; set; }
        public virtual Prov_Compra Prov_Compra { get; set; }
        public virtual Venta_Factura Venta_Factura { get; set; }
    }
}
