//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta_Transaccion
    {
        public int id { get; set; }
        public string tipo_transaccion { get; set; }
        public Nullable<int> referencia_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cliente_id { get; set; }
        public Nullable<int> proveedor_id { get; set; }
    
        public virtual Venta_Cliente Venta_Cliente { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
