//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta_CxP
    {
        public int id_CxP { get; set; }
        public int IdCompra { get; set; }
        public decimal SaldoAnterior { get; set; }
        public decimal Abono { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Prov_Compra Prov_Compra { get; set; }
    }
}
