//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta_CxC
    {
        public int id_CxC { get; set; }
        public int IdFactura { get; set; }
        public decimal SaldoAnterior { get; set; }
        public decimal Abono { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Venta_Factura Venta_Factura { get; set; }
    }
}
