//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Capacitacion_Participantes
    {
        public int id { get; set; }
        public Nullable<int> capacitacion_id { get; set; }
        public Nullable<int> participante_id { get; set; }
        public Nullable<int> calificacion { get; set; }
        public string retroalimentacion { get; set; }
    
        public virtual Emp_Capacitacion Emp_Capacitacion { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
