//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Capacitacion_Participantes
    {
        public int id { get; set; }
        public Nullable<int> capacitacion_id { get; set; }
        public Nullable<int> participante_id { get; set; }
        public Nullable<int> calificacion { get; set; }
        public string retroalimentacion { get; set; }
    
        public virtual Emp_Capacitacion Emp_Capacitacion { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
