//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_BitacoraIngreso
    {
        public int id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
    }
}
