//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_ContactoEmergencia
    {
        public int id { get; set; }
        public Nullable<int> empleado_id { get; set; }
        public string nombre_contacto { get; set; }
        public string telefono_contacto { get; set; }
        public string relacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
