//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Conta_Transaccion = new HashSet<Conta_Transaccion>();
            this.Emp_ContactoEmergencia = new HashSet<Emp_ContactoEmergencia>();
            this.Emp_RemuneracionDeduccion = new HashSet<Emp_RemuneracionDeduccion>();
            this.SolicitudesVacaciones = new HashSet<SolicitudesVacaciones>();
            this.Notificaciones = new HashSet<Notificaciones>();
            this.Notificaciones_usuario = new HashSet<Notificaciones_usuario>();
            this.PDA_Tarea = new HashSet<PDA_Tarea>();
            this.PDA_Tarea1 = new HashSet<PDA_Tarea>();
            this.PDA_Tarea2 = new HashSet<PDA_Tarea>();
            this.PDA_Tarea3 = new HashSet<PDA_Tarea>();
            this.PlanDeAccion = new HashSet<PlanDeAccion>();
            this.Prov_Pago = new HashSet<Prov_Pago>();
            this.Ticket = new HashSet<Ticket>();
            this.Ticket1 = new HashSet<Ticket>();
            this.Venta_Carrito = new HashSet<Venta_Carrito>();
            this.PDA_Tarea4 = new HashSet<PDA_Tarea>();
            this.Emp_Capacitacion_Participantes = new HashSet<Emp_Capacitacion_Participantes>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string numero_identificacion { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public Nullable<int> departamento_id { get; set; }
        public Nullable<int> puesto_id { get; set; }
        public Nullable<int> rol_id { get; set; }
        public Nullable<bool> estado_empleado { get; set; }
        public string usuario { get; set; }
        public byte[] contrasena { get; set; }
    
        public virtual Adm_Rol Adm_Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conta_Transaccion> Conta_Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_ContactoEmergencia> Emp_ContactoEmergencia { get; set; }
        public virtual Emp_Departamento Emp_Departamento { get; set; }
        public virtual Emp_Puesto Emp_Puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_RemuneracionDeduccion> Emp_RemuneracionDeduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesVacaciones> SolicitudesVacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones_usuario> Notificaciones_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDA_Tarea> PDA_Tarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDA_Tarea> PDA_Tarea1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDA_Tarea> PDA_Tarea2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDA_Tarea> PDA_Tarea3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDeAccion> PlanDeAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prov_Pago> Prov_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Carrito> Venta_Carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDA_Tarea> PDA_Tarea4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Capacitacion_Participantes> Emp_Capacitacion_Participantes { get; set; }
    }
}
