//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entregas
    {
        public int id { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string direccion_entrega { get; set; }
        public string articulos_entregados { get; set; }
        public string observaciones_adicionales { get; set; }
    
        public virtual Venta_Factura Venta_Factura { get; set; }
    }
}
