//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entregas
    {
        public int id { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string direccion_entrega { get; set; }
        public string articulos_entregados { get; set; }
        public string observaciones_adicionales { get; set; }
    
        public virtual Venta_Pedido Venta_Pedido { get; set; }
    }
}
