//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosFinancieros
    {
        public int Id { get; set; }
        public int ProveedorId { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
