//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosFinancieros
    {
        public int Id { get; set; }
        public int ProveedorId { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
