//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPedido
    {
        public int PedidoId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string DetalleCambio { get; set; }
        public int EstadoCompraId { get; set; }
    
        public virtual EstadoCompra EstadoCompra { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
