//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialModificacion
    {
        public int PedidoId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string DetallesModificacion { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
