//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones_usuario
    {
        public int id { get; set; }
        public int id_notificacion { get; set; }
        public int id_usuario_recibe { get; set; }
        public bool lectura { get; set; }
        public Nullable<System.DateTime> fecha_lectura { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Notificaciones Notificaciones { get; set; }
    }
}
