//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones_usuario
    {
        public int id { get; set; }
        public int id_notificacion { get; set; }
        public int id_usuario_recibe { get; set; }
        public bool lectura { get; set; }
        public Nullable<System.DateTime> fecha_lectura { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Notificaciones Notificaciones { get; set; }
    }
}
