//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notificaciones()
        {
            this.Notificaciones_usuario = new HashSet<Notificaciones_usuario>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_mensaje_basico { get; set; }
        public string mensaje_final { get; set; }
        public int id_modulo { get; set; }
        public Nullable<int> prioridad { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<int> id_usuario_registro { get; set; }
        public Nullable<int> id_objeto_referencia { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Modulos Modulos { get; set; }
        public virtual Notificaciones_basicas Notificaciones_basicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones_usuario> Notificaciones_usuario { get; set; }
    }
}
