//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_Tarea
    {
        public int id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public string descripcion_tarea { get; set; }
        public Nullable<int> responsable_id { get; set; }
        public Nullable<int> estado_tarea { get; set; }
        public Nullable<int> calificacion { get; set; }
        public string observacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Empleado Empleado2 { get; set; }
        public virtual Empleado Empleado3 { get; set; }
        public virtual Empleado Empleado4 { get; set; }
        public virtual PDA_Estado PDA_Estado { get; set; }
        public virtual PDA_Estado PDA_Estado1 { get; set; }
        public virtual PlanDeAccion PlanDeAccion { get; set; }
        public virtual PlanDeAccion PlanDeAccion1 { get; set; }
    }
}
