//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_Tarea
    {
        public int id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public string descripcion_tarea { get; set; }
        public Nullable<int> responsable_id { get; set; }
        public Nullable<int> estado_tarea { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Empleado Empleado2 { get; set; }
        public virtual Empleado Empleado3 { get; set; }
        public virtual Empleado Empleado4 { get; set; }
        public virtual PDA_Estado PDA_Estado { get; set; }
        public virtual PDA_Estado PDA_Estado1 { get; set; }
        public virtual PlanDeAccion PlanDeAccion { get; set; }
        public virtual PlanDeAccion PlanDeAccion1 { get; set; }
    }
}
