//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_Tarea
    {
        public int id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public string descripcion_tarea { get; set; }
        public Nullable<int> responsable_id { get; set; }
        public string estado_tarea { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual PlanDeAccion PlanDeAccion { get; set; }
    }
}
