//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDeAccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanDeAccion()
        {
            this.PDA_Tarea = new HashSet<PDA_Tarea>();
        }
    
        public int id { get; set; }
        public string nombre_plan { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
        public string descripcion_plan { get; set; }
        public Nullable<int> CategoriaPlanId { get; set; }
        public Nullable<int> EstadoAccionId { get; set; }
        public Nullable<int> TipoAccionId { get; set; }
        public Nullable<int> ResponsableId { get; set; }
    
        public virtual CategoriaPlan CategoriaPlan { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual PDA_Estado PDA_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDA_Tarea> PDA_Tarea { get; set; }
        public virtual PDA_TipoAccion PDA_TipoAccion { get; set; }
    }
}
