//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prov_Contacto
    {
        public int id { get; set; }
        public Nullable<int> proveedor_id { get; set; }
        public string nombre_contacto { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public string descripcion_adicional { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
