//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prov_Contacto
    {
        public int id { get; set; }
        public Nullable<int> proveedor_id { get; set; }
        public string nombre_contacto { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public string descripcion_adicional { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
