//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prov_Pago
    {
        public int id { get; set; }
        public Nullable<int> proveedor_id { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<decimal> monto_pago { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> autorizador_id { get; set; }
        public Nullable<int> compra_id { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Prov_Compra Prov_Compra { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
