//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id_ticket { get; set; }
        public int id_usuario { get; set; }
        public int estado { get; set; }
        public int tipo_incidencia { get; set; }
        public Nullable<int> prioridad { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_registro_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registra_tecnico { get; set; }
        public Nullable<int> id_tecnico { get; set; }
        public string comentario_tecnico { get; set; }
        public Nullable<System.DateTime> fecha_cierre_ticket { get; set; }
        public string comentarios_usuario { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Ticket_Estado Ticket_Estado { get; set; }
        public virtual Ticket_Prioridad Ticket_Prioridad { get; set; }
        public virtual Ticket_Tipo Ticket_Tipo { get; set; }
    }
}
