//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta_FacturaDetalle
    {
        public int id { get; set; }
        public Nullable<int> factura_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unidad { get; set; }
    
        public virtual Venta_Factura Venta_Factura { get; set; }
        public virtual Venta_Producto Venta_Producto { get; set; }
    }
}
