//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta_FacturaDetalle
    {
        public int id { get; set; }
        public Nullable<int> factura_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unidad { get; set; }
    
        public virtual Venta_Factura Venta_Factura { get; set; }
        public virtual Venta_Producto Venta_Producto { get; set; }
    }
}
